Feature/#533 highest volume auctions
gnosis/ido-ux pull request #687
Opened 2021-06-14 13:02 UTC by maria-vslvn

1. Highest volume auctions table at the mane page created
2. added mobile view
3. featured auctions data was used as mockdata

2021-06-14 13:26 UTC, ramirotw commented on src/components/auctions/HighestVolumeAuctions/index.tsx
> +              <StyledTd>{moment(new Date()).format('DD/MM/YYYY')}</StyledTd>
let's just use Date's `toLocaleDateString` for formatting and also remove momentjs library from the dependencies to reduce the bundle size

2021-06-14 19:53 UTC, josojo commented
Cool, looks already good.

Here are some suggestions:
Could we get the same column highlighting, as we have currently on the auction overview table?
Could we get the whole column clickable, and not just the > symbol?
Ammount -> Amount
Improve the mobile mode to something that looks better?
![image](https://user-images.githubusercontent.com/7348154/121951161-d89f4780-cd5a-11eb-836f-b4d45dcfdf30.png)
Maybe @alongoni can help here too

2021-06-15 11:31 UTC, elena-zh commented
Hi @maria-vslvn , @josojo , 
I have reviewed the changes, and here are mu notes: 
1. It would be nice to improve the landing page layout as currently we have different paddings between sections: 
![different paddings](https://user-images.githubusercontent.com/70885163/122043309-dc2ae100-cde3-11eb-9b9a-97a3c5c018a1.jpg)
So, it would be good to have the same one between all the sections.

2. All the lines in the table are sorted in the BE by usdAmountTraded desc. However, sorting seems to be incorrect. See on the 4 and 5 lines: for  4 line tje usdAmountTraded = 5, for 5th line  usdAmountTraded=9. 
![usdamounttraded](https://user-images.githubusercontent.com/70885163/122043861-8145b980-cde4-11eb-9686-3e5d8602acfb.jpg)

3. From my perspective, 'End Date' is not clear to be when see an auction details in the mobile view. I see a date, but I, as an end user, have no clue what date it is: ending/auction creation/etc. Could we add a label for this field?
![image](https://user-images.githubusercontent.com/70885163/122044196-e6011400-cde4-11eb-97e6-d1d766f43003.png)

4. Cards in the 'Featured Auctions' and 'Highest Volume Auctions' have different width in mobile/tablet view on a certain screen resolutions. I think, cards should look the same
![the same width](https://user-images.githubusercontent.com/70885163/122044339-0fba3b00-cde5-11eb-9ca5-3ab3e2754769.jpg)

5. This case might be fixed by the previous one, however, I will mention it. We have 5 auctions in the table, so on a certain screen resolutions we may get a bit not pretty view with an empty space from the right. I think, it would be nice to show whether 4 or 6 auction in order to avoid this case:
![4 or 6](https://user-images.githubusercontent.com/70885163/122044729-83f4de80-cde5-11eb-829f-643091c6f1d5.jpg)

6. The last case.. We do not have a task for a logic implementation for this table. Currently, 'Featured auctions' are displayed in the table..

Thanks

2021-06-15 17:51 UTC, alongoni commented
Hey @maria-vslvn @josojo 
Regarding point 1) I suggest use this margin/paddings
![02- GnosisAuction - Landing v2](https://user-images.githubusercontent.com/622217/122100032-1945a200-cde9-11eb-87fc-f4c7f15b8ee1.png)


For points 3) and 4) Here are some options to show the info in cards.
![image](https://user-images.githubusercontent.com/622217/122095135-5c047b80-cde3-11eb-9334-28ba42af56b8.png)

2021-06-16 09:47 UTC, maria-vslvn commented
1. same as "All auctions" row highlghting.
2. the  whole column was made clickable.
3. ammount -> amount.
4. moment lib was removed.
5. new indents were made between the landing sections.
6. all cards were made of the same width  on mob view.
7. new styles for highest vol auctions cards were applied for mob view, i applied the second variant.

2021-06-16 11:11 UTC, josojo commented
> Hey @maria-vslvn @josojo
> Regarding point 1) I suggest using this margin/paddings
> ![02- GnosisAuction - Landing v2](https://user-images.githubusercontent.com/622217/122100032-1945a200-cde9-11eb-87fc-f4c7f15b8ee1.png)
> 
> For points 3) and 4) Here are some options to show the info in cards.
> ![image](https://user-images.githubusercontent.com/622217/122095135-5c047b80-cde3-11eb-9334-28ba42af56b8.png)

Yes I like the margins a lot.
I like the third option card the best

2021-06-16 12:01 UTC, elena-zh commented
Hey @maria-vslvn , @alongoni , @josojo , 
I have verified the issue. Great job! 
The only thing I have to mention in addition to Alex comment about the 3rd option, is that it would be nice to center-align fields in the auction card as it is done for a featured auction card 
![image](https://user-images.githubusercontent.com/70885163/122215202-9dfcf280-ceb3-11eb-8907-f28ebbcc7060.png)

Cases 2 and 5 from my previous comment I have moved to #690 task. 

Thanks

2021-06-16 15:26 UTC, maria-vslvn commented
@josojo @elena-zh i've updated the auction card to 4variant. according to centering the data, i've spent some time on it, and it takes time to implement and show the visual center. if we really need this i can spent some more time

2021-06-16 15:56 UTC, elena-zh commented
@maria-vslvn , I have created a separate issue for fields alignment inside an auction card #695. 
Card's layout is changed and LGTM. 
Thanks!

2021-06-16 18:02 UTC, alongoni requested changes
Looks really good! I made two little suggestions. Thanks.

2021-06-25 11:01 UTC, merged